### ISSUE TITLE
normal shell mode?

### ISSUE THREAD

**Issue by yitang** [IvanMalison/term-manager#2]
Hi,

I never used ansi-term before and it seems rather strange, I can't even use M-x ... inside of the ansi-term buffer. I wonder how could I use the normal shell mode? 

Thanks,

Yi

**Comment by colonelpanic8** [comment]
I do this in my configuration of term-mode

``` emacs-lisp
(use-package term
  :bind (:map term-raw-escape-map
              ("M-x" . helm-M-x))
  :bind (:map term-raw-map
              ("M-x" . helm-M-x))
  :config
  (progn
    (add-hook 'term-mode-hook 'imalison:disable-linum-mode)
    (setq term-buffer-maximum-size 0)))
```

So that I can use M-x in term-mode

With that said, term-manager/projectile can allow you to use shell instead of ansi-term pretty easily

All you have to do is set the build-term property of 'term-projectile-term-manager

I think something like 

``` emacs-lisp
(oset term-projectile-term-manager build-term
      (lambda (directory-symbol)
        (let ((default-directory (symbol-name directory-symbol)))
          (shell))))
```

would work.

**Comment by yitang** [comment]
@IvanMalison setting the build-term property gives me the shell, thanks.
